image: registry.cn-beijing.aliyuncs.com/kenny_ci/python-go:3.12-1.21
stages:
  - test
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
    - __pypackages__/
    - /root/.cache/pdm
variables:
  PROJECT: 'hodl'
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  TEST_FULL_DATA: 'brief'

before_script:
  - mkdir -p ~/logs/hodl && mkdir -p ~/data/hodl && cp tests/ci/gitlab-ci.toml config.toml
  - pip install -U pdm
  - pdm config python.use_venv false && pdm install --prod -G test --no-lock --no-editable && pdm sync

test:
  stage: test
  tags:
    - python
  only:
    - branches
    - tags
  script:
    - pdm run test
    - pdm run report
    - pdm run xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:
  stage: build
  tags:
    - python
  only:
    - tags
  when: manual
  script:
    - pdm build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  artifacts:
    paths:
      - dist/*.whl
