html_file_path = 'demo.html'

[store.FAKE]
broker = 'fakeBroker'
symbol = 'FAKE'
name = '此处是名称'
trade_type = 'stock'
currency = 'USD'
enable = true
max_shares = 110_000
base_price_last_buy = true
factor_fear_and_greed = 'greed'
base_price_tumble_protect = true