#
#   gitlab 专用配置
#
db_path = ":memory:"

[store.TIGR]
broker = 'tiger'
symbol = 'TIGR'
trade_type = 'stock'
enable = true
max_shares = 100_000
log_root = ''
state_file_path = ''
state_archive_folder = ''
prudent = true
base_price_last_buy = true
sleep_mode = false

[store.TEST]
broker = 'tiger'
symbol = 'TEST'
currency = 'USD'
region = 'US'
trade_type = 'stock'
enable = true
max_shares = 100_000
log_root = ''
state_file_path = ''
state_archive_folder = ''
prudent = true
base_price_last_buy = true
base_price_day_low = true
sleep_mode = false
buy_spread = 0.0
sell_spread = 0.0

[store.LOCK]
broker = 'tiger'
symbol = 'LOCK'
currency = 'USD'
region = 'US'
trade_type = 'stock'
enable = true
max_shares = 100_000
log_root = ''
state_file_path = ''
state_archive_folder = ''
prudent = true
base_price_last_buy = true
sleep_mode = false
buy_spread = 0.0
sell_spread = 0.0
lock_position = true

[store.ASHARE]
broker = 'tiger'
symbol = '000001'
currency = 'CNY'
region = 'CN'
trade_type = 'stock'
enable = true
max_shares = 100_000
log_root = ''
state_file_path = ''
state_archive_folder = ''
prudent = true
base_price_last_buy = true
sleep_mode = false
buy_spread = 0.0
sell_spread = 0.0
lock_position = true

[store.BTC]
broker = 'okx'
symbol = 'BTC'
currency = 'USD'
region = 'US'
trade_type = 'crypto'
enable = true
max_shares = 300
log_root = ''
state_file_path = ''
state_archive_folder = ''
prudent = true
base_price_last_buy = true
sleep_mode = false
buy_spread = 0.0
sell_spread = 0.0
closing_time = '23:00:00'
