#
#   gitlab 专用配置
#
db_path = ":memory:"

[store.TIGR]
broker = 'tiger'
symbol = 'TIGR'
trade_type = 'stock'
enable = true
max_shares = 100_000
log_root = ''
state_file_path = ''
state_archive_folder = ''
prudent = true
base_price_last_buy = true
sleep_mode = false

[store.TEST]
broker = 'tiger'
symbol = 'TEST'
currency = 'USD'
region = 'US'
trade_type = 'stock'
enable = true
max_shares = 100_000
log_root = ''
state_file_path = ''
state_archive_folder = ''
prudent = true
base_price_last_buy = true
base_price_day_low = true
sleep_mode = false
buy_spread = 0.0
sell_spread = 0.0
sell_order_rate = 0.01
buy_order_rate = 0.01

[store.ASHARE]
broker = 'tiger'
symbol = '000001'
currency = 'CNY'
region = 'CN'
trade_type = 'stock'
enable = true
max_shares = 100_000
log_root = ''
state_file_path = ''
state_archive_folder = ''
prudent = true
base_price_last_buy = true
sleep_mode = false
buy_spread = 0.0
sell_spread = 0.0
lock_position = true
shares_per_unit = 100
legal_rate_daily = 0.1

[store.BTC]
broker = 'okx'
symbol = 'BTC'
currency = 'USD'
region = 'US'
trade_type = 'crypto'
enable = true
max_shares = 300
log_root = ''
state_file_path = ''
state_archive_folder = ''
prudent = true
base_price_last_buy = true
sleep_mode = false
buy_spread = 0.0
sell_spread = 0.0
closing_time = '23:00:00'

[[broker_meta.tiger]]
trade_type = 'stock'
share_market_state = true
share_quote = true
market_status_regions = ['US', 'HK', 'CN', ]
quote_regions = ['US', 'HK', ]
trade_regions = ['US', 'HK', ]
vix_symbol = 'VIX'
